# ~/.bash_aliases

# File system (eza)
if command -v eza &> /dev/null; then
  alias ls="eza -lh --group-directories-first --icons=auto"
  alias lsa="ls -a"
  alias lt="eza --tree --level=2 --long --icons --git"
  alias lta="lt -a"
  alias l="eza -lah --group-directories-first --icons=auto"
  alias ll="eza -lh --group-directories-first --icons=auto"
  alias la="eza -a --group-directories-first --icons=auto"
fi

# Bat / Cat
if command -v bat &> /dev/null; then
  alias cat="bat --paging=never"
fi

# FZF + Bat file finder
if command -v fzf &> /dev/null && command -v bat &> /dev/null; then
  alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
  alias eff='$EDITOR "$(ff)"'
fi

# Zoxide smart directory switching
if command -v zoxide &> /dev/null; then
  alias cd="zd"
  zd() {
    if (( $# == 0 )); then
      builtin cd ~ || return
    elif [[ -d $1 ]]; then
      builtin cd "$1" || return
    else
      if ! z "$@"; then
        echo "Error: Directory not found"
        return 1
      fi
      printf "\U000F17A9 "
      pwd
    fi
  }
fi

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Dev & Git
alias g="git"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gcad="git commit -a --amend"
alias lg="lazygit"
alias d="docker"
alias t="tmux attach || tmux new -s Work"
alias top="btop"
alias n="nvim"
n() { if [ "$#" -eq 0 ]; then command nvim . ; else command nvim "$@"; fi; }

# Work directories shortcuts
alias cdw="cd ~/Work"
alias cdd="cd ~/Work/dev"
alias cdp="cd ~/Work/projects"
alias cdwt="cd ~/Work/worktrees"
